---
apiVersion: v1
baseDomain: cefaslocalserver.com
metadata:
  name: okd-cluster
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - cidr: 172.30.0.0/16
platform:
  none: {}
  flip: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"","email":"amccrae@redhat.com"},"quay.io":{"auth":"","email":"amccrae@redhat.com"},"registry.connect.redhat.com":{"auth":"","email":"amccrae@redhat.com"},"registry.redhat.io":{"auth":"","email":"amccrae@redhat.com"},"registry.svc.ci.openshift.org":{"auth": ""}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC9XqGWEd2de3Ud8TgvzFchK2/SYh+WHohA1KEuveXjCbse9aXKmNAZ369vaGFFGrxbSptMeEt41ytEFpU09gAXM6KSsQWGZxfkCJQSWIaIEAdft7QHnTpMeronSgYZIU+5P7/RJcVhHBXfjLHV6giHxFRJ9MF7n6sms38VsuF2s4smI03DWGWP6Ro7siXvd+LBu2gDqosQaZQiz5/FX5YWxvuhq0E/ACas/JE8fjIL9DQPcFrgQkNAv1kHpIWRqSLPwyTMMxGgFxGI8aCTH/Uaxbqa7Qm/aBfdG2lZBE1XU6HRjAToFmqsPJv4LkBxaC1Ag62QPXONNxAA97arICr vhgalvez@gmail.com'
