apiVersion: v1
baseDomain: cefaslocalserver.com
metadata:
  name: okd-cluster
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - cidr: 172.30.0.0/16
platform:
  none: {}
  flip: false
pullSecret: |
  {
      "auths":{
          "cloud.openshift.com":{
              "auth":"openshift-release-dev+ocm_access_e993db7c003d41e48fde8da49b1ffda2:ZHL2NGQQSKMZKRII0O0NZS1ZIX0AOFM3CB7PRLL279S4Y7PJI0TEWRAHKHQYURNS",
              "email":"vhgalvez@gmail.com"
          },
          "quay.io":{
              "auth":"openshift-release-dev+ocm_access_e993db7c003d41e48fde8da49b1ffda2:ZHL2NGQQSKMZKRII0O0NZS1ZIX0AOFM3CB7PRLL279S4Y7PJI0TEWRAHKHQYURNS",
              "email":"vhgalvez@gmail.com"
          },
          "registry.connect.redhat.com":{
              "auth":"|uhc-pool-c579a8d9-07bb-40f7-9981-ce84effad26a:eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI0ODc1YTUwMjJiNmM0YmJjYjEwMWEwOTc3MTAxMGI5YiJ9.YcCQJ_WzWc-Aq5W4S9F4q7j3snOCzTfoutLtKKND_4V0g6QgFz6puhz7ZUra3S1lRJmQtVYBDO1REkiOkBbDzPEjT-OHmfH8Gp4gNSwLnIe4sygV1C1YpHSSgRWgqiZhPs1YPLbWk8z3K_8JMfXmmK2U-xtuXxUins--Z74wx07UXLmwe0VOC7DNX003AF-LalV9nv8yULZv3JRgGEc8XnFFq9ck5jBWfdTxIwUNtPGazAphQgKurYh-dfaZKfJ0iTIVEyF0cGOCYkOFQ4SjIDO9olmfhczKDnR28BRwd-PNIpAsJOmydYF5GtgS5kcdOfWgeuLqb9nQmr0Q1mzsvhansljwq4WmEHZXRuuZ46E9qeV1x3eNuC42rQywwARtluRp5zOjoR7ubdqGNWj-22Y6rn-ziV_mtAWTtxClf3OU9j5bC-M257Huh7XkupRxmfXpulJjgdifBR2hcG1SPV0qOjAf075TFeNXsjNNVgAhEoef-1-0w8XhHIWZePWOYrDofGw_pMdrVjYeTw_qHj_C00kiHJhN2AP_2QBt30sauQnbM5sx6XjYR0j4CCE2ZH3IvCNaaMPwkxbxkAZ7von8rY3kf00ktZpXfN2OX4xlsEZicgLz4RcWdG4YU4n6p2eyTO1bB8JXFdiN3YBcabB78ZgSV9lyYYnvu4ZrkYE",
              "email":"vhgalvez@gmail.com"
          },
          "registry.redhat.io":{
              "auth":"|uhc-pool-c579a8d9-07bb-40f7-9981-ce84effad26a:eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI0ODc1YTUwMjJiNmM0YmJjYjEwMWEwOTc3MTAxMGI5YiJ9.YcCQJ_WzWc-Aq5W4S9F4q7j3snOCzTfoutLtKKND_4V0g6QgFz6puhz7ZUra3S1lRJmQtVYBDO1REkiOkBbDzPEjT-OHmfH8Gp4gNSwLnIe4sygV1C1YpHSSgRWgqiZhPs1YPLbWk8z3K_8JMfXmmK2U-xtuXxUins--Z74wx07UXLmwe0VOC7DNX003AF-LalV9nv8yULZv3JRgGEc8XnFFq9ck5jBWfdTxIwUNtPGazAphQgKurYh-dfaZKfJ0iTIVEyF0cGOCYkOFQ4SjIDO9olmfhczKDnR28BRwd-PNIpAsJOmydYF5GtgS5kcdOfWgeuLqb9nQmr0Q1mzsvhansljwq4WmEHZXRuuZ46E9qeV1x3eNuC42rQywwARtluRp5zOjoR7ubdqGNWj-22Y6rn-ziV_mtAWTtxClf3OU9j5bC-M257Huh7XkupRxmfXpulJjgdifBR2hcG1SPV0qOjAf075TFeNXsjNNVgAhEoef-1-0w8XhHIWZePWOYrDofGw_pMdrVjYeTw_qHj_C00kiHJhN2AP_2QBt30sauQnbM5sx6XjYR0j4CCE2ZH3IvCNaaMPwkxbxkAZ7von8rY3kf00ktZpXfN2OX4xlsEZicgLz4RcWdG4YU4n6p2eyTO1bB8JXFdiN3YBcabB78ZgSV9lyYYnvu4ZrkYE",
              "email":"vhgalvez@gmail.com"
          }
      }
  }
sshKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC9XqGWEd2de3Ud8TgvzFchK2/SYh+WHohA1KEuveXjCbse9aXKmNAZ369vaGFFGrxbSptMeEt41ytEFpU09gAXM6KSsQWGZxfkCJQSWIaIEAdft7QHnTpMeronSgYZIU+5P7/RJcVhHBXfjLHV6giHxFRJ9MF7n6sms38VsuF2s4smI03DWGWP6Ro7siXvd+LBu2gDqosQaZQiz5/FX5YWxvuhq0E/ACas/JE8fjIL9DQPcFrgQkNAv1kHpIWRqSLPwyTMMxGgFxGI8aCTH/Uaxbqa7Qm/aBfdG2lZBE1XU6HRjAToFmqsPJv4LkBxaC1Ag62QPXONNxAA97arICr vhgalvez@gmail.com"